### PR TITLE
Making new errors

### PR DESCRIPTION
**Pull request by aterebinski**
This is description, Show me more...

### CODE REVIEW

**Review by tryb77 — COMMENTED** [review]
fixed error by tryb

**Comment by tryb77** [comment]
its free

**Review by tryb77 — COMMENTED** [review]
I'll check it

**Review by tryb77 — CHANGES_REQUESTED** [review]
Give me some changes

**Review by aterebinski — COMMENTED** [review]
i've done some fix

**Review by tryb77 — APPROVED** [review]
I approve

**Pull request merged**
